[package]
name = "random-lp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
rand = "*"
rand_chacha = "*"
ndarray = "*"
good_lp = "*"
